name: Build Multi-Platform Spring Boot Image

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64, linux/arm/v5]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Permissions for Gradle wrapper
        run: chmod +x gradlew

      - name: Get the version
        run: echo "VERSION=$(./gradlew properties -q | grep '^version:' | awk '{print $2}')" >> $GITHUB_ENV

      - name: Set IMAGE_PLATFORM environment variable
        run: echo "IMAGE_PLATFORM=${{ matrix.platform }}" >> $GITHUB_ENV

      - name: Build Boot Image with Buildpacks
        run: ./gradlew bootBuildImage

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME  }}
          password: ${{ secrets.DOCKERHUB_TOKEN  }}

      - name: Push to GitHub Container Registry
        run: |
          docker tag docker.io/library/${{ github.repository }}:${{ env.VERSION }} ${{ vars.DOCKERHUB_USERNAME }}/${{ github.repository }}:latest
          docker tag docker.io/library/${{ github.repository }}:${{ env.VERSION }} ${{ vars.DOCKERHUB_USERNAME }}/${{ github.repository }}:${{ github.ref_name }}-${{ env.VERSION }}
          docker push ${{ vars.DOCKERHUB_USERNAME }}/${{ github.repository }}:latest
          docker push ${{ vars.DOCKERHUB_USERNAME }}/${{ github.repository }}:${{ github.ref_name }}-${{ env.VERSION }}
